Update dependency management
RockefellerArchiveCenter/scorpio pull request #141
Opened 2021-06-30 19:11 UTC by helrond

- Adds dependabot configs
- Updates pre-commit configs
- separates out top-level requirements to `requirements.in`

2021-07-01 13:22 UTC, p-galligan approved these changes
This looks good, but I'm a little unsure about why it was necessary to create a migration based on the dependencies update.

What was updated here that required it?

2021-07-01 13:26 UTC, helrond commented
I believe it's the updated version of asterism.

2021-07-01 20:44 UTC, HaSistrunk approved these changes

2021-07-02 20:32 UTC, bonniegee requested changes

2021-07-02 20:32 UTC, bonniegee commented on .pre-commit-config.yaml
> +  rev: 6.0.1
I think this can be updated to 6.2.0?

2021-07-07 13:33 UTC, HaSistrunk commented on requirements.in
> +Django==3.2.4
Django 3.2.5?

2021-07-13 20:56 UTC, bonniegee approved these changes

2021-07-13 20:58 UTC, merged