CI updates
RockefellerArchiveCenter/scorpio pull request #146
Opened 2021-09-21 17:31 UTC by p-galligan

Updates readme and travis file for CI updates

2021-09-21 20:28 UTC, helrond requested changes
Couple of really minor things.

2021-09-21 20:28 UTC, helrond commented on .travis.yml
>      - SERVICE_NAME: scorpio-web
I know this is nitpicky but can we call this $CONTAINER so it's consistent across apps?

2021-09-21 20:28 UTC, helrond commented on .travis.yml
> +  on: &development
This looks like an inadvertent add.

2021-09-21 21:33 UTC, helrond approved these changes

2021-09-22 14:23 UTC, HaSistrunk approved these changes

2021-09-28 18:00 UTC, bonniegee approved these changes

2021-09-28 19:08 UTC, merged